# Generated by Django 5.1.4 on 2025-03-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_id_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regno',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
