# Generated by Django 5.1.4 on 2025-03-05 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='regno',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
