# Generated by Django 5.1.4 on 2025-03-05 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_regno'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementOffer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('cgpa_required', models.DecimalField(decimal_places=2, max_digits=4)),
                ('no_of_backpapers', models.PositiveIntegerField(default=0)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('skillset', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('posted_date', models.DateField()),
                ('final_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('tutor_id', models.AutoField(primary_key=True, serialize=False)),
                ('tutor_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.PositiveIntegerField()),
                ('division', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('reg_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('batch', models.CharField(max_length=20)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.user')),
                ('tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='main.tutor')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('appli_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=50)),
                ('applied_date', models.DateField()),
                ('offer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.placementoffer')),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.student')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('backlog', models.PositiveIntegerField(default=0)),
                ('sem', models.PositiveIntegerField()),
                ('reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='main.student')),
            ],
            options={
                'unique_together': {('reg_no', 'sem')},
            },
        ),
    ]
