# Generated by Django 5.1.4 on 2025-03-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_placementoffer_tutor_student_application_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='division',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
